import turtle
from time import *


def drawSquare(myTurtle, x, y, size,myColor = "black",angle = 0):
    myTurtle.penup()
    myTurtle.color(myColor)
    myTurtle.goto(x, y)
    myTurtle.setheading(90)
    myTurtle.left(angle)
    myTurtle.pendown()
    myTurtle.begin_fill()
    myTurtle.right(90)
    myTurtle.forward(size)
    myTurtle.right(90)
    print(myTurtle.pos())
    myTurtle.forward(size)
    myTurtle.right(90)
    myTurtle.forward(size)
    myTurtle.right(90)
    myTurtle.forward(size)
    myTurtle.end_fill()

def drawTriangle(myTurtle,x,y,cathetus,myColor = "black",angle = 0):
    hypothenuse = (cathetus**2 + cathetus**2)**0.5
    myTurtle.penup()
    myTurtle.color(myColor)
    myTurtle.goto(x, y)
    myTurtle.setheading(90)
    myTurtle.pendown()
    myTurtle.begin_fill()
    myTurtle.right(angle)
    myTurtle.right(45)
    myTurtle.forward(hypothenuse)
    myTurtle.right(135)
    myTurtle.forward(cathetus)
    myTurtle.right(90)
    myTurtle.forward(cathetus)
    myTurtle.end_fill()

def drawParallelogram(myTurtle,x,y,shortside,longside,myColor = "black",angle = 0):
    myTurtle.penup()
    myTurtle.color(myColor)
    myTurtle.goto(x, y)
    myTurtle.setheading(90)
    myTurtle.pendown()
    myTurtle.begin_fill()
    myTurtle.right(angle)
    myTurtle.right(45)
    myTurtle.forward(shortside)
    myTurtle.right(135)
    myTurtle.forward(longside)
    myTurtle.right(45)
    myTurtle.forward(shortside)
    myTurtle.right(135)
    myTurtle.forward(longside)
    myTurtle.end_fill()

ada = turtle.Turtle()
drawTriangle(ada,100,100,40,"orange",225)
drawTriangle(ada,100,100,56,"orange",180)
drawTriangle(ada,100,100,79,"orange",135)
drawTriangle(ada,100,-11,79,"orange",135)
sleep(1000)
