import turtle
from time import *

#print(myTurtle.pos())

def drawSquare(myTurtle, x, y, size,myColor = "black",angle = 0):
    myTurtle.penup()
    myTurtle.color(myColor)
    myTurtle.goto(x, y)
    myTurtle.setheading(90)
    myTurtle.left(angle)
    myTurtle.pendown()
    myTurtle.begin_fill()
    myTurtle.right(90)
    myTurtle.forward(size)
    myTurtle.right(90)
    print(myTurtle.pos())
    myTurtle.forward(size)
    myTurtle.right(90)
    myTurtle.forward(size)
    myTurtle.right(90)
    myTurtle.forward(size)
    myTurtle.end_fill()

def drawTrianglefill(myTurtle,x,y,cathetus,myColor = "black",angle = 0):
    hypothenuse = (cathetus**2 + cathetus**2)**0.5
    myTurtle.penup()
    myTurtle.color(myColor)
    myTurtle.goto(x, y)
    myTurtle.setheading(90)
    myTurtle.pendown()
    myTurtle.begin_fill()
    myTurtle.right(angle)
    myTurtle.right(45)
    myTurtle.forward(hypothenuse)
    myTurtle.right(135)
    myTurtle.forward(cathetus)
    myTurtle.right(90)
    myTurtle.forward(cathetus)
    myTurtle.end_fill()

def drawTriangle(myTurtle,x,y,cathetus,myColor = "black",angle = 0):
    hypothenuse = (cathetus**2 + cathetus**2)**0.5
    myTurtle.penup()
    myTurtle.color(myColor)
    myTurtle.goto(x, y)
    myTurtle.setheading(90)
    myTurtle.pendown()
    myTurtle.right(angle)
    myTurtle.right(45)
    myTurtle.forward(hypothenuse)
    myTurtle.right(135)
    myTurtle.forward(cathetus)
    myTurtle.right(90)
    myTurtle.forward(cathetus)

def drawTriangleDebug(myTurtle,x,y,cathetus,myColor = "black",angle = 0):
    hypothenuse = (cathetus**2 + cathetus**2)**0.5
    myTurtle.penup()
    myTurtle.color(myColor)
    myTurtle.goto(x, y)
    print(myTurtle.pos())
    myTurtle.setheading(90)
    myTurtle.pendown()
    myTurtle.right(angle)
    myTurtle.right(45)
    myTurtle.forward(hypothenuse)
    print(myTurtle.pos())
    myTurtle.right(135)
    myTurtle.forward(cathetus)
    print(myTurtle.pos())
    myTurtle.right(90)
    myTurtle.forward(cathetus)

def drawParallelogram(myTurtle,x,y,shortside,longside,myColor = "black",angle = 0):
    myTurtle.penup()
    myTurtle.color(myColor)
    myTurtle.goto(x, y)
    myTurtle.setheading(90)
    myTurtle.pendown()
    #myTurtle.begin_fill()
    myTurtle.right(angle)
    myTurtle.right(45)
    myTurtle.forward(shortside)
    myTurtle.right(135)
    myTurtle.forward(longside)
    myTurtle.right(45)
    myTurtle.forward(shortside)
    myTurtle.right(135)
    myTurtle.forward(longside)
    #myTurtle.end_fill()

ada = turtle.Turtle()
drawTrianglefill(ada,100,-50,40,"orange",225)
drawTrianglefill(ada,100,-50,56,"orange",180)
drawTrianglefill(ada,100,-50,79,"orange",135)
drawTrianglefill(ada,44,-218,79,"orange",180+135)
drawTriangle(ada,0,-261,100,"black",0)
drawTrianglefill(ada,100,-261,56,"orange",180)
drawTrianglefill(ada,44,-317,56,"orange",0)
drawTriangle(ada,100,-161,50,"black",90)
drawTriangle(ada,150,-211,50,"black",270)
drawTriangle(ada,100,-111,50,"black",90)
drawTriangle(ada,150,-161,50,"black",270)
drawTrianglefill(ada,150,-111,35,"black",225)
drawTriangle(ada,100,-211,50,"black",90)
drawTriangle(ada,150,-261,50,"black",270)
drawTriangle(ada,150,-161,100,"black",90)
drawSquare(ada,100,-261,50,"black",0)
drawParallelogram(ada,150,-311,25,60,"black",-45)
sleep(1000)
